intents-operator/templates/ValidatingWebhookConfiguration.yaml, intents-operator/templates/clientintents-customresourcedefinition.yaml, intents-operator/templates/intents-operator-manager-clusterrole.yaml, intents-operator/templates/kafkaserverconfigs-customresourcedefinition.yaml
This PR updates the crd, cluster role and webhook files which are auto-generated in client intents repo, they are identical expect the indentation and item order change
There is no changes required in docs
=> Update client intents auto generated files

intents-operator/templates/intents-operator-deployment.yaml, intents-operator/values.yaml
Exposing the cloud credentials of the intents operator to the helm values
=> Expose cloud credentials as helm values

intents-operator/README.md, intents-operator/templates/intents-operator-deployment.yaml, intents-operator/values.yaml, network-mapper/README.md, network-mapper/templates/mapper-deployment.yaml, network-mapper/values.yaml, otterize-kubernetes/README.md, otterize-kubernetes/values.yaml
=> Preparation for Otterize Cloud release

intents-operator/templates/intents-operator-deployment.yaml
Fixing this error:
```
Error: UPGRADE FAILED: YAML parse error on otterize-kubernetes/charts/intentsOperator/templates/intents-operator-deployment.yaml: error converting YAML to JSON: yaml: line 24: did not find expected key
```
=> Fixed a bug when setting enableEnforcement to false

otterize-kubernetes/Chart.yaml, otterize-kubernetes/README.md, otterize-kubernetes/values.yaml
https://www.notion.so/otterize/Add-network-mapper-to-main-otterize-kubernetes-chart-d26b27e9a2de4de7b48c33bcb8e5e18b
=> Added network mapper to otterize-kubernetes helm chart

intents-operator/templates/kafkaserverconfigs-customresourcedefinition.yaml
Add enum for Kafka pattern generated by kube-builder in intents-operator
=> Create Kafka pattern literal

credentials-operator/README.md, credentials-operator/values.yaml, intents-operator/README.md, intents-operator/values.yaml, network-mapper/README.md, network-mapper/values.yaml, otterize-kubernetes/README.md, otterize-kubernetes/values.yaml
Document custom root CA configuration in helm charts READMEs
=> Document custom root CA configuration in helm charts READMEs

network-mapper/README.md, network-mapper/templates/_helpers.tpl, network-mapper/templates/exp/istio-watcher-clusterrole.yaml, network-mapper/templates/exp/istio-watcher-deployment.yaml, network-mapper/templates/exp/istio-watcher-serviceaccount.yaml, network-mapper/values.yaml
Added Istio watcher templates to network-mapper helm charts + readme edits to match.
=> Add Istio watcher templates (exp)

otterize-kubernetes/values.yaml
Adding Istio watcher field to otterize-kubernetes `values.yaml`
=> Adding Istio watcher field to otterize-kubernetes values.yaml

intents-operator/README.md, intents-operator/templates/intents-operator-deployment.yaml, intents-operator/values.yaml, network-mapper/README.md, network-mapper/templates/mapper-clusterrole.yaml, network-mapper/templates/mapper-deployment.yaml, network-mapper/values.yaml, otterize-kubernetes/README.md, otterize-kubernetes/values.yaml
Add a key to disable telemetry collection. by setting it to `true` a telemetry disable flag will be added to intents operator execution arguments.
=> Add a key for disabling telemetry collection

network-mapper/templates/mapper-deployment.yaml
Fix templating syntax in mapper-deployment.yaml
=> Fix templating syntax in mapper-deployment.yaml

otterize-kubernetes/values.yaml
Enable Istio support by default
=> Enable istio policies by default

credentials-operator/templates/credentials-operator-leader-election-role.yaml, credentials-operator/templates/credentials-operator-leader-election-rolebinding.yaml, credentials-operator/templates/credentials-operator-manager-clusterrole.yaml, credentials-operator/templates/credentials-operator-manager-clusterrolebinding.yaml, credentials-operator/templates/credentials-operator-metrics-reader-clusterrole.yaml, credentials-operator/templates/credentials-operator-proxy-clusterrole.yaml, credentials-operator/templates/credentials-operator-proxy-clusterrolebinding.yaml, intents-operator/templates/ValidatingWebhookConfiguration.yaml, intents-operator/templates/intents-operator-leader-election-role.yaml, intents-operator/templates/intents-operator-leader-election-rolebinding.yaml, intents-operator/templates/intents-operator-manager-clusterrole.yaml, intents-operator/templates/intents-operator-manager-clusterrolebinding.yaml, intents-operator/templates/intents-operator-metrics-reader-clusterrole.yaml, intents-operator/templates/intents-operator-proxy-clusterrole.yaml, intents-operator/templates/intents-operator-proxy-clusterrolebinding.yaml
Add 'otterize-' prefix to cluster-scoped resources (cluster roles, validation hooks, etc.)
=> Add 'otterize-' prefix to cluster scoped resources

network-mapper/templates/mapper-deployment.yaml
Fix a typo in network-mapper's deployment
=> Fix a typo in network-mapper's deployment

.github/workflows/e2e-test.yaml
Add a simple test that installs otterize-kubernetes (with the default configuration) and check that it gets to a ready state
=> Add an e2e sanity test github action

credentials-operator/templates/deployment.yaml, credentials-operator/values.yaml, intents-operator/templates/intents-operator-deployment.yaml, intents-operator/values.yaml, network-mapper/values.yaml, otterize-kubernetes/values.yaml, spire/templates/agent-daemonset.yaml, spire/templates/server-statefulset.yaml, spire/values.yaml
This PR makes all images configurable using values, so that offline image mirrors may be used.
=> Make all images in Helm charts configurable using values

intents-operator/Chart.yaml, intents-operator/crds/clientintents-customresourcedefinition.yaml, intents-operator/crds/kafkaserverconfigs-customresourcedefinition.yaml, intents-operator/crds/protectedservices-customresourcedefinition.yaml, intents-operator/templates/intents-operator-manager-clusterrole.yaml, intents-operator/templates/otterize-validating-webhook-configuration.yaml, network-mapper/Chart.yaml
Following the introduction of the new [API version](https://github.com/otterize/intents-operator/pull/259), there have been changes to the intent operator chart. 
https://github.com/otterize/intents-operator/pull/259
=> Create new intents API version: v1alpha3

intents-operator/crds/clientintents-customresourcedefinition.yaml, intents-operator/templates/otterize-validating-webhook-configuration.yaml
This PR fixes previous merge problems.
=> Fix status field and bad validating webhook config

network-mapper/Chart.yaml, network-mapper/templates/istio-watcher-deployment.yaml, network-mapper/templates/kafka-watcher-deployment.yaml, network-mapper/templates/sniffer-daemonset.yaml
Add client id for sniffer and watchers to enrich error reporting
=> Add client id to sniffers and watchers

.github/workflows/bump-version.yaml, otterize-kubernetes/Chart.yaml
Add a conditional rule to the version bump workflow.
This will disable automatic version bumping if we add "nobump" as part of the commit message
- Documentation: This is part of the ci/cd flow of the repository and does not require additional documentation in the docs
=> Add nobump rule to auto commit version workflow

intents-operator/crds/clientintents-customresourcedefinition.yaml
Related to https://github.com/otterize/intents-operator/pull/329
=> Add observedGeneration field to ClientIntents Status field

intents-operator/templates/_helpers.tpl, intents-operator/templates/intents-operator-deployment.yaml
Use environment variables instead of program arguments in the intents-operator deployment
https://github.com/otterize/intents-operator/pull/330
=> Use environment variables instead of program arguments in the intents-operator deployment

intents-operator/templates/_helpers.tpl, intents-operator/templates/intents-operator-deployment.yaml
Reverts otterize/helm-charts#156
=> Revert "Use environment variables instead of program arguments in the intents-operator deployment"

intents-operator/templates/intents-operator-deployment.yaml
… creation
Use the right environment variable for enabling egress network policy creation
=> Use the right environment variable for enabling egress network policy creation

credentials-operator/templates/credentials-operator-deployment.yaml, credentials-operator/templates/credentials-operator-serviceaccount.yaml, intents-operator/templates/intents-operator-controller-manager-serviceaccount.yaml
Azure support fixes: unquote arguments & fix confused names
Follow up on https://github.com/otterize/helm-charts/pull/175
=> Azure support fixes: unquote arguments & fix confused names

intents-operator/crds/clientintents-customresourcedefinition.yaml, intents-operator/crds/kafkaserverconfigs-customresourcedefinition.yaml, intents-operator/crds/protectedservices-customresourcedefinition.yaml
Fix intents-operator helm charts - missing copy-manifests-to-helm execution after intents operator CRD changes
=> Fix intents-operator helm charts - missing copy-manifests-to-helm execution after intents operator CRD changes

credentials-operator/README.md, credentials-operator/templates/credentials-operator-deployment.yaml, credentials-operator/templates/credentials-operator-serviceaccount.yaml, credentials-operator/values.yaml, intents-operator/README.md, intents-operator/templates/intents-operator-controller-manager-serviceaccount.yaml, intents-operator/templates/intents-operator-deployment.yaml, intents-operator/values.yaml, otterize-kubernetes/README.md, otterize-kubernetes/values.yaml
Move shared Azure integration arguments to "global" values, to avoid having to pass them around twice
=> Move shared Azure integration arguments to "global" values

credentials-operator/templates/credentials-operator-aws-mutating-webhook-configuration.yaml
Accompanies https://github.com/otterize/credentials-operator/pull/122
=> Fix issue running AWS webhooks alongside GCP and Azure simultaneously

network-mapper/templates/mapper-deployment.yaml
Add pod namespace to mapper deployment unconditionally
=> Add pod namespace to mapper deployment unconditionally 

credentials-operator/templates/credentials-operator-manager-clusterrole.yaml, intents-operator/crds/postgresqlserverconfigs-customresourcedefinition.yaml, intents-operator/templates/intents-operator-manager-clusterrole.yaml, intents-operator/templates/otterize-validating-webhook-configuration.yaml
Adding PGSQL CRDs, webhooks, and update operator permissions
=> Adding PGSQL CRDs, webhooks, and update operator permissions  

.github/workflows/e2e-test-azure-iam.yaml, .github/workflows/e2e-test-database-integrations.yaml
Provide GITHUB_TOKEN to GoTestTools/gotestfmt-action to void rate limiting
https://github.com/GoTestTools/gotestfmt
=> Provide GITHUB_TOKEN to GoTestTools/gotestfmt-action to void rate limiting

.github/workflows/e2e-test.yaml, .github/workflows/release.yaml
Fix e2e-tests from release workflow call - pass secrets
=> Fix e2e-tests from release workflow call - pass secrets

credentials-operator/README.md, credentials-operator/templates/credentials-operator-deployment.yaml, credentials-operator/values.yaml
Include any links supporting this change such as a:
- GitHub Issue/PR number addressed or fixed
- StackOverflow post
- Related pull requests/issues from other repos
If there are no references, simply delete this section.
=> Adding secret rotation interval entry in credentials operator values.yaml

credentials-operator/Chart.yaml, intents-operator/Chart.yaml, network-mapper/Chart.yaml, otterize-kubernetes/Chart.yaml
Please see the [contributing guidelines](CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo. This template is based on Auth0's excellent template.
Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
Include any links supporting this change such as a:
- GitHub Issue/PR number addressed or fixed
- StackOverflow post
- Related pull requests/issues from other repos
If there are no references, simply delete this section.
=> Revert last release

credentials-operator/Chart.yaml, intents-operator/Chart.yaml, network-mapper/Chart.yaml
Set the chart's app versions to the last release versions.
=> Set appVersions to the last release versions

credentials-operator/Chart.yaml, intents-operator/Chart.yaml, network-mapper/Chart.yaml
=> Revert app versions to the last stable OSS releases

network-mapper/Chart.yaml
Revert to the previous network-mapper release
=> Revert to the previous network-mapper release

network-mapper/Chart.yaml
Update network-mapper app version to the latest release
=> Update network-mapper app version to the latest release

intents-operator/templates/intents-operator-manager-clusterrole.yaml
Adding linkerd resources to clusterrole
=> Adding linkerd resources to clusterrole

.github/workflows/e2e-test.yaml, intents-operator/templates/intents-operator-webhook-server-deployment.yaml, intents-operator/templates/validation-webhook-service.yaml, intents-operator/values.yaml, tests/base_suite.go
Accompanying PR to https://github.com/otterize/intents-operator/pull/567.
=> Move webhook server into separate pod to resolve situations where there can be a circular dependency by the intents operator on itself
