network-mapper/templates/_helpers.tpl
network-mapper/templates/mapper-configmap.yaml
network-mapper/templates/mapper-role.yaml
network-mapper/templates/mapper-serviceaccount.yaml

This PR supports the same change in the network mapper repo, see there for the full details:
https://github.com/otterize/network-mapper/pull/40

Saving the network mapper state into a config map for persistency

---

intents-operator/templates/intents-operator-deployment.yaml
intents-operator/values.yaml
otterize-kubernetes/values.yaml

This PR adds the enableEnforcement helm value to the operator, which can be used in order to disable all the enforcement abilities of the intents operator at once.
Goes together with the intents-operator PR: https://github.com/otterize/intents-operator/pull/101

Added the enableEnforcement flag to disable of all types of enforcement in one place

---

intents-operator/README.md
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/values.yaml
network-mapper/README.md
network-mapper/templates/mapper-deployment.yaml
network-mapper/values.yaml
otterize-kubernetes/README.md
otterize-kubernetes/values.yaml

Exposes the cloud connectivity parameters in the same manner for both intents-operator and network-mapper
Also updated in docs, and added to otterize-Kubernetes helm chart

Aligned cloud values in intents-operator and network-mapper

---

spire/README.md
spire/templates/agent-daemonset.yaml
spire/values.yaml

This PR uses Otterize's mirror of SPIRE images for cases where a corporate firewall blocks access to gcr.io.

Use mirrored SPIRE images

---

spire/Chart.yaml
spire/templates/scripts-configmap.yaml
spire/templates/server-statefulset.yaml

SPIRE 1.0.2 has an issue on minikube 1.29.0 that makes the spire-agent fail to create the required entities using the k8s selector, and causes the credentials-operator to crash-loop as it fails to access SPIRE.
This PR upgrades the spire image to the latest version (1.5.4), which supports the minikube 1.29.0.
Because the new image doesn't have a shell, we used a sidecar to run the init commands instead of `postStart`.

Fix SPIRE issue when running on latest minikube version

---

credentials-operator/templates/_helpers.tpl
credentials-operator/templates/deployment.yaml
credentials-operator/values.yaml
intents-operator/templates/_helpers.tpl
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/values.yaml
network-mapper/templates/_helpers.tpl
network-mapper/templates/mapper-deployment.yaml
network-mapper/values.yaml
otterize-kubernetes/values.yaml

Support custom root CAs when initializing cloud client - provide root CA secret reference via helm charts

Support custom root CAs when initializing cloud client - provide root CA secret reference via helm charts

---

intents-operator/Chart.yaml
intents-operator/templates/clientintents-customresourcedefinition.yaml
intents-operator/templates/kafkaserverconfigs-customresourcedefinition.yaml

This is the first step for moving CRDs out of `templates` dir to their own dedicated directory, `crds`, as [helm best practices suggest](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/).
Addresses part one of this [issue](https://github.com/otterize/intents-operator/issues/134).

Add helm 'keep' annotation to not remove CRDs in helm uninstall.

---

credentials-operator/templates/credentials-operator-client-secret.yaml
credentials-operator/templates/deployment.yaml
intents-operator/templates/intents-operator-client-secret.yaml
intents-operator/templates/intents-operator-deployment.yaml
network-mapper/templates/mapper-client-secret.yaml
network-mapper/templates/mapper-deployment.yaml
otterize-kubernetes/Chart.yaml

Prior to this PR, when passed by values, the client secret would be passed as an environment variable rather than a Secret.

Bugfix: Use Secret to store Otterize Cloud client secret

---

otterize-kubernetes/values.yaml

Add internal aliases for networkMapper components in otterize-k8s helm chart, in order to allow configuration them via flags passed on helm install, like so:
```
helm upgrade -i otterize -n otterize-system --create-namespace ./  --set networkMapper.kafkawatcher.enable=true --set networkMapper.kafkawatcher.kafkaServers="kafka-0.kafka"
```

Add internal aliases for networkMapper components in otterize-k8s helm chart

---

credentials-operator/Chart.yaml
credentials-operator/templates/deployment.yaml
credentials-operator/values.yaml
intents-operator/Chart.yaml
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/templates/watcher-deployment.yaml
intents-operator/values.yaml
network-mapper/Chart.yaml
network-mapper/templates/exp/kafka-watcher-deployment.yaml
network-mapper/templates/mapper-deployment.yaml
network-mapper/templates/sniffer-daemonset.yaml
network-mapper/values.yaml

Use chart.appVersion for intents-operator, credentials-operator, and network-mapper, image tags instead of using "latest".

Use chart.AppVersion as default image tag instead of using latest

---

intents-operator/templates/intents-operator-manager-clusterrole.yaml

The intents operator will need GET permissions for namespaces to perform get operation on "kube-system"  for its UID (that will be used as cluster identifier).

Add get permission to the intents-operator clusterRole file

---

network-mapper/values.yaml

Pin istio-watcher's image tag to the chart's app version instead of the latest tag.

Pin istio-watcher image tag to chart.AppVersion instead of latest

---

credentials-operator/README.md
intents-operator/templates/intents-operator-deployment.yaml
network-mapper/templates/mapper-deployment.yaml

Configure the telemetry flag for both true and false values. This way the helm chart is independent of the app defaults.
https://github.com/otterize/intents-operator/pull/178

Configure the telemetry flag for both true and false values

---

network-mapper/templates/mapper-deployment.yaml

Use string type in environment variables. (true -> "true")

Use string type in environment variables

---

intents-operator/templates/intents-operator-manager-clusterrole.yaml

Changes in resource order result from auto-generating the file from the operator source code instead of manually editing, which also fixed some bad indentations.

Add 'update CRD' permission to intents-operator

---

network-mapper/Chart.yaml
network-mapper/README.md
network-mapper/templates/sniffer-daemonset.yaml
network-mapper/values.yaml

Adding the option to add tolerations and priority class name to network mapper daemon set, so the network mapper could be added to the entire nodes in the cluster
Include any links supporting this change such as a:
- GitHub Issue/PR number addressed or fixed
https://github.com/otterize/helm-charts/issues/92
- [  ] I have added documentation for new/changed functionality in this PR and in github.com/otterize/docs

add tolerations and priority class name to network-mapper daemon set

---

network-mapper/templates/sniffer-daemonset.yaml

Allows the network sniffer to read the HOSTNAME environment variable, which is used for verifying the pod identity.

Add SYS_PTRACE capability to network sniffer

---

intents-operator/README.md
intents-operator/crds/clientintents-customresourcedefinition.yaml
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/values.yaml

Add support for the new experimental database reconciler (coming soon!) and its feature flag.
https://github.com/otterize/docs/pull/108

Add experimental support for the new database reconciler and its feature flag.

---

intents-operator/templates/intents-operator-manager-clusterrole.yaml

Following the release of "protected-services" feature, the operator needs the permissions to create CRD in order to create the protectedService CRD.

Add crd create permissions to intents-operator-manager-clusterrole.yaml

---

intents-operator/templates/intents-operator-deployment.yaml

This PR fixes a bug where the intents operator chart did not mount the TLS certificates in the right location when using cert-manager.

Fix cert-manager file mount locations

---

intents-operator/templates/_helpers.tpl

Update the default certificate path to reflect that SPIRE is no longer recommended.

Update default certificate path for intents operator

---

intents-operator/values.yaml
otterize-kubernetes/values.yaml

Pod watcher is no longer an independent deployment

Remove unused watcher object

---

network-mapper/templates/istio-watcher-deployment.yaml
network-mapper/templates/kafka-watcher-deployment.yaml
network-mapper/templates/mapper-deployment.yaml
network-mapper/templates/sniffer-daemonset.yaml

Related: https://github.com/otterize/network-mapper/pull/139

Add liveness and readiness checks to mapper components, as well as tighter security context restrictions

---

network-mapper/templates/istio-watcher-deployment.yaml
network-mapper/templates/kafka-watcher-deployment.yaml
network-mapper/templates/sniffer-daemonset.yaml

On slow Minikube clusters, mapper components could take longer to start, causing data loss initially when they were restarted, which effectively resulted in the network map being slow to populate.

Increase initialDelaySeconds for mapper components liveness and readiness

---

network-mapper/README.md
network-mapper/templates/mapper-deployment.yaml
network-mapper/values.yaml

This PR adds support for configuring the OpenTelemetry exporter that exports Grafana Tempo-style metrics, contributed by @smithclay from Lightstep/ServiceNow in https://github.com/otterize/network-mapper/pull/141.
https://github.com/otterize/network-mapper/pull/141

Support for configuring the OpenTelemetry exporter

---

intents-operator/README.md
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/values.yaml

This PR adds experimental support for the generation of egress network policies, to be used together with an egress default deny policy.
The intents operator can now generate egress network policies to pods, or to pods at specific ports, if a Kubernetes service is targeted using intents.
References
https://github.com/otterize/intents-operator/pull/256

Add configuration for experimental egress network policy support

---

intents-operator/templates/intents-operator-deployment.yaml

The helm chart used a wrong name to enable AWS integration. This commit changes the name to the correct one.

Fix helm value name for intents operator

---

credentials-operator/templates/deployment.yaml
credentials-operator/values.yaml
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/values.yaml
otterize-kubernetes/values.yaml

With https://github.com/otterize/intents-operator/pull/290 the cluster name should only be specified for overriding.

Allow specifying override EKS cluster name; otherwise autodetect from environment

---

network-mapper/templates/kafka-watcher-deployment.yaml
network-mapper/values.yaml

Enable the option to configure Kafka report intervals using Helm values. 
This feature is documented only in the chart description since it's a low level feature for testing who shouldn't be changed in normal use.

Expose Kafka report intervals configuration using Helm values

---

network-mapper/templates/kafka-watcher-deployment.yaml
network-mapper/values.yaml

This PR revert an update to Kafka watcher values, that was add without an update to chart version to keep the previous version as it was. The changed will be added later with a version update

Revert change without version: Kafka watcher configuration update

---

intents-operator/templates/intents-operator-deployment.yaml
network-mapper/templates/mapper-deployment.yaml
otterize-kubernetes/Chart.yaml

Previously, the credentials operator was not deployed by default. This is because to do anything at all, it required a certificate provider - Otterize Cloud, a SPIRE server, or cert-manager. The credentials operator now also manages AWS IAM roles and links Kubernetes service accounts, so it is functional on its own.
This PR also fixes a problem where the Deployment for the network-mapper did not declare its ports.

Always deploy credentials operator (required for AWS), declare ports for network mapper

---

intents-operator/values.yaml
otterize-kubernetes/Chart.yaml
otterize-kubernetes/README.md
otterize-kubernetes/values.yaml

In a previous PR #138, the credentials operator chart was set to default on, since the AWS IAM feature requires it, which makes the credentials-operator useful even if you don't use mTLS.
However, this was done through removing the condition in the otterize-kubernetes chart to depend on the credentials-operator chart, and the documentation was also not updated :(
This PR re-adds the condition so that users can still disable the chart if they want to for whatever reason, and corrects the documentation.

Fix credentials operator deployment documentation, and re-add credentials operator deployment condition with different default

---

network-mapper/README.md
network-mapper/templates/mapper-deployment.yaml
network-mapper/values.yaml

Accompanying PR for https://github.com/otterize/network-mapper/pull/161. This is a temporary flag that enables the Internet-facing traffic reporting.

Add support for enabling the reporting of Internet-facing traffic

---

network-mapper/Chart.yaml
network-mapper/templates/_helpers.tpl
network-mapper/templates/component-config-map.yaml
network-mapper/templates/istio-watcher-deployment.yaml
network-mapper/templates/kafka-watcher-deployment.yaml
network-mapper/templates/mapper-clusterrole.yaml
network-mapper/templates/mapper-deployment.yaml
network-mapper/templates/sniffer-daemonset.yaml

Allow sharing the mapper context id with the other components who don't call directly to the control plane.

Allow reporting errors with context id from sniffer and watchers

---

intents-operator/crds/clientintents-customresourcedefinition.yaml

This pull request introduces a new intent type designed to manage access to internet addresses. Specifically, for this intent type, the name field is made optional. Due to the limitations of the CRD schema in enforcing the name field requirement based on intent type, the enforcement of this requirement will be handled in the webhook server logic within the operator repository.
- Documentation: This is part of egress network policy feature which is still experimental and will be documented when the feature is released

Add internet intent type to CRD

---

.github/workflows/bump-version.yaml
otterize-kubernetes/Chart.yaml

Allow otterizebot to directly bump Helm chart versions on main branch
Documentation: This is part of the ci/cd flow of the repository and does not require additional documentation in the docs

Add otterizebot token for version bump

---

intents-operator/crds/clientintents-customresourcedefinition.yaml
intents-operator/crds/kafkaserverconfigs-customresourcedefinition.yaml
intents-operator/crds/protectedservices-customresourcedefinition.yaml
intents-operator/templates/intents-operator-manager-clusterrole.yaml
intents-operator/templates/otterize-validating-webhook-configuration.yaml

Add otterize labels to custom resources and webhooks to allow controllers to filter out and reconcile relevant resources 
[Fix operator redeployment overwrite issues and ensure webhook configs and CRDs consistency](https://github.com/otterize/intents-operator/pull/338)

Add Otterize labels to CRDs and webhooks

---

intents-operator/templates/intents-operator-manager-clusterrole.yaml

The intents-operator reconciles `ValidatingWebhookConfiguration` labeled with Otterize labels to update their CA to the self-signed one created by the Operator.
https://github.com/otterize/intents-operator/pull/344/files

Add RBAC watch permissions of `ValidatingWebhookConfiguration` to the intents-operator-manager `ClusterRole`

---

intents-operator/crds/clientintents-customresourcedefinition.yaml
network-mapper/templates/mapper-clusterrole.yaml

This PR expand the ability to specify intents to the internet to support specifying intents to DNS and generate Egress network policies to their IP address. This PR update the CRD and the network mapper RBAC permission to allow it update the ClientIntents status field.
[The intents operator relevant PR
](https://github.com/otterize/intents-operator/pull/353)
Egress is an experimental feature, full documentation will be add once the egress support will be officially released.

Add support for specifying intents for Internet domain names

---

network-mapper/templates/mapper-deployment.yaml
network-mapper/values.yaml

This commit matches the default setting for generating self signed certificate to those of intents operator and credentials operator (that is, generate by default).

Generate self signed certificates for network mapper webhook by default

---

intents-operator/crds/clientintents-customresourcedefinition.yaml

changing the internet dns name field from:
```
spec:
calls:
- type: internet
dns: api.datadoghq.com
```
to
```
spec:
calls:
- type: internet
domains: 
- api.datadoghq.com
```
[Intents operator PR](https://github.com/otterize/intents-operator/pull/358)

Change internet DNS field to Domains list

---

network-mapper/templates/mapper-deployment.yaml
network-mapper/values.yaml

Add feature flag for enabling DNS intents update by the mapper
[Related Network Mapper PR](https://github.com/otterize/network-mapper/pull/184)
This feature will be documented with the official release of DNS intents

Add DNS intents feature flag

---

credentials-operator/templates/credentials-operator-mutating-webhook-configuration.yaml
credentials-operator/templates/credentials-operator-webhook-service.yaml

Apply the credentials-operator webhook when either IAM providers is enabled - AWS, GCP or Azure. 
Known issue: this won't work when more than one IAM provider is enabled, but that'll be fixed in a separate task (it requires splitting the webhooks to one for each IAM provider).

Apply the credentials-operator webhook when either IAM providers is enabled

---

spire/templates/_helpers.tpl

Quick fix for what I consider a typo in the spire chart `templates/_helpers.tpl` `spire.fullname` define:
The if statement was pointing to `.Values.global.spire.fullNameOverride` but the output statement was pointing to `.Values.fullnameOverride`.
This was not allowing me to override 'smoothly' the spire resource names.

fix SPIRE chart helper spire.fullname pointing to wrong .Values.global.spire.fullNameOverride

---

credentials-operator/templates/credentials-operator-mutating-webhook-configuration.yaml

Rename create-azure-role-assignment label to create-azure-workload-identity for compatibility with other IAM providers
https://github.com/otterize/intents-operator/pull/378

Rename create-azure-role-assignment label to create-azure-workload-identity for compatibility with other IAM providers

---

credentials-operator/Chart.yaml
credentials-operator/templates/credentials-operator-deployment.yaml
credentials-operator/templates/credentials-operator-serviceaccount.yaml
intents-operator/Chart.yaml
intents-operator/crds/clientintents-customresourcedefinition.yaml
intents-operator/crds/kafkaserverconfigs-customresourcedefinition.yaml
intents-operator/crds/protectedservices-customresourcedefinition.yaml
intents-operator/templates/intents-operator-controller-manager-serviceaccount.yaml
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/templates/intents-operator-manager-clusterrole.yaml
intents-operator/templates/otterize-validating-webhook-configuration.yaml
network-mapper/Chart.yaml
otterize-kubernetes/Chart.yaml

This PR adds support for creating AWS IAM RolesAnywhere profiles based on a configured RolesAnywhere Trust Anchor (CA cert) and SPIFFE trust domain, both managed by cert-manager.
When combined with the credentials-operator and the instructions in https://github.com/otterize/otterize-csi-spiffe-demo, this can be used to achieve simple cross-cloud access.
This also temporarily brings back the old code that was moved to credentials.go in the intents-operator.
Related:
* https://github.com/otterize/intents-operator/pull/372
* https://github.com/otterize/credentials-operator/pull/117

Add support for AWS IAM RolesAnywhere with cert-manager csi-driver-spiffe, which enables cross-cloud AWS IAM access

---

credentials-operator/templates/credentials-operator-manager-clusterrole.yaml

Add additional permissions for Google Cloud to the service account controller to be able to modify namespaces and cloud config CRDs

 Add additional permissions for Google Cloud to the service account controller

---

network-mapper/templates/visibility-dns-webhook-config.yaml

The network mapper mutating webhook had the wrong component label, creating wrong certificates.

Fix network mapper webhook component label

---

intents-operator/crds/clientintents-customresourcedefinition.yaml
intents-operator/templates/intents-operator-manager-clusterrole.yaml
intents-operator/templates/otterize-validating-webhook-configuration.yaml

Support Azure Key Vault access policy in ClientIntents. 
Example intents:
```yaml
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
name: client
namespace: otterize-tutorial-azure-iam
spec:
service:
name: client
calls:
- name: "/providers/Microsoft.KeyVault/vaults/testkeyvault" 
type: azure
azureKeyVaultPolicy:
certificatePermissions:
- "all"
keyPermissions:
- "all"
secretPermissions:
- "all"
storagePermissions:
- "get"
- "delete"
```
https://github.com/otterize/intents-operator/pull/390

Azure Key Vault policy support #390

---

intents-operator/crds/clientintents-customresourcedefinition.yaml
intents-operator/crds/kafkaserverconfigs-customresourcedefinition.yaml
intents-operator/crds/postgresqlserverconfigs-customresourcedefinition.yaml
intents-operator/crds/protectedservices-customresourcedefinition.yaml

The double quotes have no effect and the file is generated by `kustomize` without them.

Remove double quotes from annotations

---

intents-operator/templates/otterize-validating-webhook-configuration.yaml

Please see the [contributing guidelines](CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo. This template is based on Auth0's excellent template.
It seems there's a duplicate of the `app.kubernetes.io/component` label in the ValidatingWebhook for the intents-operator. This might not cause issues for deploying to Kubernetes, but it's causing my Kpt pipeline to fail. I hope there aren't any extra changes i must make for a PR. Otherwise tell me, and i'll add it to the branch :)
- [N/A] I have added documentation for new/changed functionality in this PR and in github.com/otterize/docs

Remove duplicate instance of `app.kubernetes.io/component`

---

credentials-operator/templates/credentials-operator-deployment.yaml
credentials-operator/values.yaml
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/values.yaml

Support passing extraEnvVars on all three components. Used for specifying HTTP_PROXY, HTTPS_PROXY, etc.

Support for passing extraEnvVars for intents-operator & credentials-operator (previously only supported for network-mapper)

---

network-mapper/templates/mapper-deployment.yaml
network-mapper/values.yaml

The mapper should by default update client intents with DNS resolution data to support intents to domain names server. It was only disabled by default until the full support of egress feature.

Enable DNS intents support by default

---

.github/workflows/bump-version.yaml

Bugfix: fix "Tag version" step in bump-version workflow - input tag message
Fixes a bug in https://github.com/otterize/helm-charts/pull/217

Bugfix: fix "Tag version" step in bump-version workflow - input tag message

---

.github/workflows/release.yaml

Fix e2e tests trigger from release workflow
Bug originated in https://github.com/otterize/helm-charts/pull/217

Fix e2e tests trigger from release workflow

---

network-mapper/README.md
network-mapper/templates/iamlive-deployment.yaml
network-mapper/templates/visibility-dns-deployment.yaml
network-mapper/values.yaml

This pull request adds a helm value for network-mapper to override IAMLive & the Visibility CoreDNS deployments resource requests/limits.

CoreDNS & IAMlive resource limits/requests

---

.github/workflows/e2e-test.yaml

Add workflow_dispatch trigger to e2e-tests workflow, to support executing them manually with custom operator tags.

Add workflow_dispatch trigger to e2e-tests

---

README.md

Fix the 'release' badge status shown in the README file. 
This was broken because the release action now happens on tags, and not on main, and so the reference to the default branch name (main) was broken. 
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-branch-parameter

Fix README 'release' badge status

---

intents-operator/templates/extended-config-configmap.yaml

This change fixes a bug when combining IAM roles anywhere configuration with ingress controller configuration, rendering a broken configmap for the intents operator. 
Prior to this change, the generated configmap looks as follows: 
```
---
apiVersion: v1
kind: ConfigMap
metadata:
name: intents-operator-config
namespace: infra
labels:
app.kubernetes.io/version: 3.0.13
annotations:
app.kubernetes.io/version: 3.0.13
data:
config.yaml: |-
aws:
- account: "..."
roleARN: ...
profileARN: ...
trustAnchorARN: ...
trustDomain: ...
ingressControllers:  # <--- this line is missing one space for indentation
- name: ...
namespace: ...
kind: ...
---
```
This file fails on yaml-to-json conversion due to a missing whitespace in the `ingressControllers:` line.

Bugfix: intents-operator configmap broken when combining IAM roles anywhere & ingress controllers configurations

---

credentials-operator/templates/rbac-certmgr.yaml
intents-operator/templates/intents-operator-leader-election-rolebinding.yaml
intents-operator/templates/rbac-certmgr.yaml

This PR includes bugfixes in the Otterize intents-operator templates for RBAC roles & role bindings, when Otterize is installed in a namespace other than otterize-system. 
Moreover, this PR fixes a wrong reference name from the `otterize-intents-operator-leader-election-rolebinding`  to `otterize-intents-operator-leader-election-role`.

Bugfixes in intents-operator helm RBAC templates for AWS IAM roles anywhere

---

credentials-operator/Chart.yaml
credentials-operator/README.md
credentials-operator/templates/credentials-operator-deployment.yaml
credentials-operator/values.yaml
otterize-kubernetes/Chart.yaml
otterize-kubernetes/README.md

Adding flag to enable secret rotation, which will be off by default in the latest credentials operator release.

Adding flag to enable secret rotation

---

intents-operator/templates/otterize-validating-webhook-configuration.yaml

The validation webhook should use the explicit version name
https://github.com/otterize/intents-operator/pull/472

Fix validation webhook paths for api version `v1beta1`

---

intents-operator/templates/intents-operator-deployment.yaml
intents-operator/values.yaml

This PR adds configuration for https://github.com/otterize/intents-operator/pull/476.

Add support for making AWS ALB ingress controllers exempt from ingress controller restrictions

---

network-mapper/Chart.yaml

Rollback [network-mapper](https://github.com/otterize/network-mapper) to version v2.0.7 due to issues detected in v2.0.8.

Rollback network-mapper to version v2.0.7

---

network-mapper/templates/sniffer-daemonset.yaml
network-mapper/values.yaml

Following changes in the network-mapper. Expose new chart value to enable extended procfs resolution feature.
https://github.com/otterize/network-mapper/pull/244

Support sniffer extended procfs resolution

---

.github/workflows/e2e-test.yaml

This fixes `Error: Resource not accessible by integration` in the e2e-test workflows for MySQL & PostgreSQL, when running on forks, such as here: https://github.com/otterize/helm-charts/pull/253 
https://github.com/dorny/test-reporter/issues/149
https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac

Fix CI issue with testing MySQL & PostgreSQL integration on forks - add missing permissions to test workflows

---

network-mapper/README.md

Just an update to the readme to document the correct key names for existing clientsecret values from pre-existing secret

fix client secret keyref value key in readme

---

network-mapper/templates/agent-daemonset.yaml
network-mapper/templates/pii-detector-deployment.yaml

Remove default image tag for node agent because the agent tag and the detector are stand-alone builds

Remove default image tag for node agent

---

intents-operator/templates/intents-operator-deployment.yaml

Fix a bug where the intents-operator did not restart even though its configmap has changed. It happened because the checksum label was placed on `Deployment.Metatdata` instead of `Deployment.Spec.template.metadata`

Fix a bug where the intents-operator did not restart even though its `configmap` has changed

---

credentials-operator/templates/credentials-operator-deployment.yaml
credentials-operator/values.yaml
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/values.yaml
network-mapper/templates/mapper-deployment.yaml
network-mapper/values.yaml

Users can now specify a key from a secret containing the client ID for templating deployments for the credentials-operator/intents-operator/network mapper

Adding support for client id in user secret for credentials

---

intents-operator/templates/intents-operator-manager-clusterrole.yaml

Sort permissions in intents-operator-manager-clusterrole.yaml to match with the output of the generate command.
https://github.com/otterize/intents-operator/pull/544

Sort permissions in intents-operator-manager-clusterrole.yaml to match with the output of the generate command

---

network-mapper/templates/agent-daemonset.yaml

Aligns node-agent with changes made to other components, so that the client id can be passed from a stored secret.
https://github.com/otterize/helm-charts/pull/269

Fix support for providing client id in user secret in node agent

---

network-mapper/templates/sniffer-daemonset.yaml
network-mapper/values.yaml

Adding sniffer readiness & liveness probes port to values.yaml. Added linkerd to mapper excluded namespaces .
Solving network mapper issue [260](https://github.com/otterize/network-mapper/issues/260)

Adding sniffer readiness & liveness probes port to values.yaml. Added linkerd to mapper excluded namespaces 

---

spire/templates/_helpers.tpl

A small fix for removing duplicate app.kubernetes.io/version labels on some resources. The duplicate labels lead to invalid yaml files. Helm seems to ignore it but if you try to install the Chart with Spire activated with kustomize you get the following error:
```
Error: map[string]interface {}(nil): yaml: unmarshal errors:
line 13: mapping key "app.kubernetes.io/version" already defined at line 11
```

fix(spire): duplicate app.kubernetes.io/version labels on some resources

---

network-mapper/templates/agent-daemonset.yaml

Removes previously used environment variables from node agent DaemonSet template.

Remove unused Azure visibility environment variables from node-agent template

---

intents-operator/templates/otterize-validating-webhook-configuration.yaml

We have revamped the format for ClientIntents to make them easier to understand and make it possible to generate more restrictive policies by default. [Read more on the docs >>](https://docs.otterize.com/reference/ClientIntents%20CRD/migrateToV2)
The two primary changes is that the word `service` is no longer used, except to mean a Kubernetes Service; before, it could mean an Otterize Service or a Kubernetes Service, which was confusing. Instead, we now use `workload` . `calls` have also been renamed `targets` , and many smaller changes to the structure to improve
What happens to your existing ClientIntents? Don’t worry, the change is backwards compatible, and nothing changes unless you explicitly upgrade. If you’re a customer, we’ll reach out to explain and plan together. If you’re using …

Support new API version for ClientIntents: v2beta1

---

credentials-operator/Chart.yaml
intents-operator/Chart.yaml
network-mapper/Chart.yaml
otterize-kubernetes/Chart.yaml

Bump major chart version on intents-operator, credentials-operator, network-mapper and otterize-kubernetes, in preparation for releasing support for ClientIntente v2. 
To learn more, [see the matching release in otterize/intents-operator](https://github.com/otterize/intents-operator/releases/tag/v3.0.0).

Support new API version for ClientIntents: v2beta1 - bump chart version

---

intents-operator/templates/intents-operator-webhook-secret.yaml

Move the secret to the right ns.
https://github.com/otterize/intents-operator/pull/560
https://github.com/otterize/helm-charts/pull/282

Move intents-operator-webhook-secret.yaml to the release namespace

---

network-mapper/templates/agent-daemonset.yaml
network-mapper/values.yaml

Allow setting custom environment variables to node-agent. Useful for setting linux, go, or internal options not exposed via helm.

Allow passing extra env variables to node-agent in helm

---

intents-operator/templates/intents-operator-deployment.yaml
intents-operator/templates/intents-operator-webhook-server-deployment.yaml

Increase health/readiness probe timeout to 5s to exceed operator cache check timeout
Include any links supporting this change such as a:
- GitHub Issue/PR number addressed or fixed
- StackOverflow post
- Related pull requests/issues from other repos
If there are no references, simply delete this section.

Increase health/readiness probe timeout to 5s to exceed operator cache check timeout

---

network-mapper/templates/mapper-clusterrole.yaml

Report network policies to the cloud for better insights on unused policies and blocked traffic
https://github.com/otterize/network-mapper/pull/285/files

Report network policies to the cloud for better insights on unused policies and blocked traffic

---

network-mapper/README.md
network-mapper/templates/agent-daemonset.yaml
network-mapper/templates/kafka-watcher-deployment.yaml
network-mapper/templates/mapper-deployment.yaml
network-mapper/templates/pii-detector-deployment.yaml
network-mapper/templates/sniffer-daemonset.yaml
network-mapper/values.yaml

This PR adds support for setting `nodeSelector` in Deployments/DaemonSet in `network-mapper` chart.
Except for `iamlive`, as I'm a bit confused about its purpose.

adds support for nodeSelector in network-mapper chart

---

credentials-operator/templates/credentials-operator-aws-mutating-webhook-configuration.yaml
credentials-operator/templates/credentials-operator-azure-mutating-webhook-configuration.yaml
credentials-operator/templates/credentials-operator-deployment.yaml
credentials-operator/templates/credentials-operator-metrics-service.yaml
credentials-operator/templates/credentials-operator-webhook-service.yaml
intents-operator/templates/intents-operator-controller-manager-metrics-service.yaml
intents-operator/templates/intents-operator-deployment.yaml
intents-operator/templates/intents-operator-webhook-server-deployment.yaml
intents-operator/templates/otterize-validating-webhook-configuration.yaml
network-mapper/templates/mapper-webhook-service.yaml

This PR fixes a bug caused by https://github.com/otterize/helm-charts/pull/304, causing Azure & AWS admission webhooks to fail on pod admission. This was caused by changing the value of the `app.kubernetes.io/component` label on the webhook configurations, which caused the webhook reconciliation process to miss them. 
- https://github.com/otterize/helm-charts/pull/304

Fix bug where Azure & AWS IAM identities are not created due to broken validating/mutating webhook configurations

---

network-mapper/templates/mapper-clusterrole.yaml

In order to support the auto-allow-webhook-traffic on Otterize cloud, the mapper needs to report which services are backed by a webhook. For this, the network mapper needs to monitor all kind of webhooks.
- [Network mapper](https://github.com/otterize/network-mapper/pull/303)

Add required permission for network mapper to report webhook service to Otterize cloud

---

intents-operator/Chart.yaml

Due to a bug detected in v3.0.16 reverting to v3.0.15 until we release a bug fix.

Revert intents-operator chart to use appVersion v3.0.15
